artifact_location: file:///Users/saadkhalid/Documents/epita/s2/ai_methodology/customer-churn-prediction-pipeline/mlflow/298182049943888927
creation_time: 1730329327442
experiment_id: '298182049943888927'
last_update_time: 1730329327442
lifecycle_stage: active
name: customer_churn_prediction_experiment
