name: churn-env
channels:
  - defaults
dependencies:
  - python=3.7
  - numpy
  - pandas
  - scikit-learn
  - mlflow
  - shap
  - xgboost
  - joblib
  - matplotlib
  - jupyterlab
  - ipython
  - notebook
  - tqdm
  - typer
  - loguru
  - black
  - flake8
  - isort
  - sphinx
  - fastapi
  - pip:
      - -e .
