artifact_uri: file:///Users/saadkhalid/Documents/epita/s2/ai_methodology/customer-churn-prediction-pipeline/mlflow/298182049943888927/9877f47ce9cc454ab63f12a2a0cd9ce6/artifacts
end_time: 1730329471034
entry_point_name: ''
experiment_id: '298182049943888927'
lifecycle_stage: active
run_id: 9877f47ce9cc454ab63f12a2a0cd9ce6
run_name: XGBoost
run_uuid: 9877f47ce9cc454ab63f12a2a0cd9ce6
source_name: ''
source_type: 4
source_version: ''
start_time: 1730329467469
status: 4
tags: []
user_id: saadkhalid
