artifact_uri: file:///Users/saadkhalid/Documents/epita/s2/ai_methodology/customer-churn-prediction-pipeline/mlflow/298182049943888927/41bd9db6e5b3488eae7a960c5c73ef82/artifacts
end_time: 1730329875127
entry_point_name: ''
experiment_id: '298182049943888927'
lifecycle_stage: active
run_id: 41bd9db6e5b3488eae7a960c5c73ef82
run_name: XGBoost
run_uuid: 41bd9db6e5b3488eae7a960c5c73ef82
source_name: ''
source_type: 4
source_version: ''
start_time: 1730329872454
status: 3
tags: []
user_id: saadkhalid
