artifact_uri: file:///Users/saadkhalid/Documents/epita/s2/ai_methodology/customer-churn-prediction-pipeline/mlflow/298182049943888927/4d9f9776171d41daa445e022da37c91f/artifacts
end_time: null
entry_point_name: ''
experiment_id: '298182049943888927'
lifecycle_stage: active
run_id: 4d9f9776171d41daa445e022da37c91f
run_name: LogisticRegression
run_uuid: 4d9f9776171d41daa445e022da37c91f
source_name: ''
source_type: 4
source_version: ''
start_time: 1730329877174
status: 1
tags: []
user_id: saadkhalid
